name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    #define o ambiente que sera usado
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Goodbye"
    
